/*
  Copyright (c) 2021, C64 <c64@gmail.com>. All rights reserved.

  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
*/

import { css, setup } from 'goober';
import React, { useEffect, useState } from 'react';
import validWords from '../../utils/valid-words';
import cc from './classnames';
import Tag from './Tag';

// initialize goober once
setup(React.createElement);

const RTIContainer = css({
  '--rtiBg': '#fff',
  '--rtiBorder': '#ccc',
  '--rtiMain': '#3182ce',
  '--rtiRadius': '0.375rem',
  '--rtiS': '0.5rem',
  '--rtiTag': '#edf2f7',
  '--rtiTagRemove': '#e53e3e',

  '*': {
    boxSizing: 'border-box',
    transition: 'all 0.2s ease',
  },

  alignItems: 'center',
  bg: 'var(--rti-bg)',
  border: '1px solid var(--rti-border)',
  borderRadius: 'var(--rti-radius)',
  display: 'flex',
  flexWrap: 'wrap',
  gap: 'var(--rti-s)',
  lineHeight: 1.4,
  padding: 'var(--rti-s)',

  '&:focus-within': {
    borderColor: 'var(--rti-main)',
    boxShadow: 'var(--rti-main) 0px 0px 0px 1px',
  },
});

const RTIInput = css({
  border: 0,
  outline: 0,
  fontSize: 'inherit',
  lineHeight: 'inherit',
  width: '50%',
});

export interface TagsInputProps {
  name?: string;
  placeHolder?: string;
  seedPhrase?: string[];
  maxTags: number;
  disabled?: boolean;
  onChange?: (tags: { text: string; textId: string }[]) => void;
  onBlur?: any;
  separators?: string[];
  onRemoved?: (tag: string) => void;
}

const defaultSeprators = ['Enter', ',', ' '];

export const TagsInput = ({
  name,
  placeHolder,
  seedPhrase,
  maxTags,
  onChange,
  onBlur,
  separators,
  disabled,
  onRemoved,
}: TagsInputProps) => {
  const [counter, incrementCounter] = useState(0);
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const [seed] = useState(seedPhrase || []);
  const [tags, setTags] = useState([
    {
      text: '',
      textId: '',
    },
  ]);

  // When creating a new Wallet, seed is autogenerated
  useEffect(() => {
    const newTags: {
      text: string;
      textId: string;
    }[] = [];

    if (seed.length > 0) {
      seed.forEach(function (word: string, index: number) {
        newTags.push({ text: word, textId: word.concat(index.toString()) });
      });
    }
    setTags(newTags);
  }, [seed]);

  useEffect(() => {
    // eslint-disable-next-line @typescript-eslint/no-unused-expressions
    onChange && onChange(tags);
  }, [onChange, tags]);

  const regexValidation = '^[a-z]+$';

  const ValidWord = (word: string) => {
    return validWords.includes(word);
  };

  const ValidText = (txt: string, rgx: string) => {
    const regex = new RegExp(rgx);
    return regex.test(txt);
  };

  const handleOnKeyUp = (e) => {
    e.stopPropagation();

    const text = e.target.value;

    if (e.key === 'Backspace' && tags.length && !text) {
      setTags(tags.slice(0, -1));
    }
    if (
      tags.length < maxTags &&
      text &&
      ValidText(text, regexValidation) &&
      ValidWord(text) &&
      (separators || defaultSeprators).includes(e.key)
    ) {
      setTags([...tags, { text, textId: `${text}`.concat(String(counter)) }]);
      incrementCounter(counter + 1);
      e.target.value = '';
      e.preventDefault();
    }
  };

  const onTagRemove = (textId) => {
    setTags(tags.filter((tag) => tag.textId !== textId));
    // eslint-disable-next-line @typescript-eslint/no-unused-expressions
    onRemoved && onRemoved(textId);
  };
  /*
   *   TODO: validate word with regex, max words.
   * */
  return (
    <div aria-labelledby={name} className={cc('rti--container', RTIContainer)}>
      {tags.map((tag) => (
        <Tag
          key={tag.textId}
          text={tag.text}
          textId={tag.text}
          remove={() => onTagRemove(tag.textId)}
          blocked={disabled}
          validText={ValidText(tag.text, regexValidation)}
          validWord={ValidWord(tag.text)}
        />
      ))}

      <input
        className={cc('rti--input', RTIInput)}
        type="text"
        name={name}
        placeholder={placeHolder}
        onKeyDown={handleOnKeyUp}
        onBlur={onBlur}
        disabled={disabled}
      />
    </div>
  );
};
