module.exports = {
  HANDLE_FETCH_DATA: 'handle-fetch-data',
  FETCH_DATA_FROM_STORAGE: 'fetch-data-from-storage',
  HANDLE_SAVE_DATA: 'handle-save-data',
  SAVE_DATA_IN_STORAGE: 'save-data-in-storage',
  SAVE_WALLET_IN_STORAGE_BY_KEY: 'save-wallet-in-storage-by-key',
  HANDLE_SAVE_WALLET: 'handle-save-wallet',
  HANDLE_REMOVE_DATA: 'handle-remove-data',
  REMOVE_DATA_FROM_STORAGE: 'remove-data-from-storage',
  REMOVE_WALLET_FROM_STORAGE_BY_KEY: 'remove-wallet-from-storage-by-key',
  HANDLE_REMOVE_WALLET: 'handle-remove-wasmV4',
  FETCH_WALLET_FROM_STORAGE_BY_KEY: 'fetch-wallet-from-storage-by-key',
  HANDLE_FETCH_WALLET: 'handle-fetch-wallet',
  FETCH_ALL_WALLETS_FROM_STORAGE: 'fetch-all-wallets-from-storage',
  HANDLE_FETCH_ALL_WALLETS: 'handle-fetch-all-wallets',
};
